"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, CheckCircle2, MessageCircle, Search, ShieldCheck } from "lucide-react";
import { countryGuides, opportunities, type RouteType } from "@/lib/scholarships";

const types: Array<"All" | RouteType> = ["All", "Scholarship", "Study portal", "Work route"];

export default function ScholarshipsPage() {
  const [query, setQuery] = useState("");
  const [type, setType] = useState<(typeof types)[number]>("All");
  const filtered = useMemo(() => opportunities.filter((item) => (type === "All" || item.type === type) && `${item.name} ${item.country} ${item.level}`.toLowerCase().includes(query.toLowerCase())), [query, type]);

  return <main className="min-h-screen bg-[#07090c] text-white">
    <header className="border-b border-white/10"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Link href="/" className="text-xl font-semibold">Earn<span className="text-cyan-400">Loop</span></Link><a href="#help" className="text-sm text-cyan-200 hover:text-cyan-100">Talk to us ↗</a></div></header>
    <div className="mx-auto max-w-6xl px-6 py-12 sm:py-16">
      <div className="max-w-3xl"><p className="text-sm font-medium text-cyan-300">The mobility desk · scholarships, study and work</p><h1 className="mt-3 text-4xl font-semibold tracking-tight sm:text-6xl">Good opportunities. Better sources.</h1><p className="mt-5 text-lg leading-8 text-slate-400">Practical, editorial-style explainers for people planning their next international study or work move. We curate official programme, university and government pages—then you apply there directly.</p></div>
      <div className="mt-10 flex flex-col gap-3 rounded-2xl border border-white/10 bg-[#0e1318] p-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-3.5 size-4 text-slate-500" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search country, degree or route" className="h-11 w-full rounded-xl bg-white/5 pl-11 pr-4 text-sm outline-none placeholder:text-slate-600 focus:ring-1 focus:ring-cyan-300/50" /></div><div className="flex gap-2 overflow-x-auto">{types.map((item) => <button key={item} onClick={() => setType(item)} className={`whitespace-nowrap rounded-xl px-3 py-2 text-sm ${type === item ? "bg-cyan-300 font-semibold text-slate-950" : "text-slate-400 hover:bg-white/5 hover:text-white"}`}>{item}</button>)}</div></div>
      <div className="mt-6 flex items-center gap-2 text-xs text-slate-500"><CheckCircle2 className="size-4 text-lime-300" /> {filtered.length} routes · links go to official sources · reviewed September 2026</div>
      <section className="mt-6 grid gap-4 lg:grid-cols-2">{filtered.map((item) => <article key={item.name} className="flex flex-col rounded-2xl border border-white/10 bg-[#0e1318] p-6"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-cyan-300/10 px-2.5 py-1 text-xs text-cyan-200">{item.type}</span><h2 className="mt-4 text-xl font-semibold">{item.name}</h2><p className="mt-1 text-sm text-slate-500">{item.country} · {item.level}</p></div><ShieldCheck className="size-5 shrink-0 text-lime-300" /></div><p className="mt-5 leading-7 text-slate-300">{item.summary}</p><div className="mt-5 grid gap-3 border-y border-white/10 py-4 text-sm sm:grid-cols-2"><div><p className="text-xs text-slate-500">Funding / route</p><p className="mt-1 text-slate-200">{item.funding}</p></div><div><p className="text-xs text-slate-500">Eligibility</p><p className="mt-1 text-slate-200">{item.eligibility}</p></div></div><p className="mt-4 text-sm leading-6 text-slate-400"><strong className="text-slate-200">How to apply:</strong> {item.howToApply}</p>{item.steps && item.documents && <details className="mt-5 rounded-xl bg-white/[.03] p-4 text-sm"><summary className="cursor-pointer font-medium text-cyan-200">Open the step-by-step checklist</summary><div className="mt-4 grid gap-5 sm:grid-cols-2"><div><p className="font-medium text-slate-200">Application steps</p><ol className="mt-2 list-decimal space-y-2 pl-5 text-slate-400">{item.steps.map((step) => <li key={step}>{step}</li>)}</ol></div><div><p className="font-medium text-slate-200">Typical documents</p><ul className="mt-2 list-disc space-y-2 pl-5 text-slate-400">{item.documents.map((document) => <li key={document}>{document}</li>)}</ul></div></div></details>}<a href={item.source} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-cyan-200 hover:text-cyan-100">{item.sourceLabel} <ArrowUpRight className="size-4" /></a></article>)}</section>
      <section className="mt-20"><p className="text-sm font-medium text-cyan-300">University discovery</p><h2 className="mt-2 text-3xl font-semibold">Start with the country portal</h2><p className="mt-3 max-w-2xl text-slate-400">Use these official portals to compare programmes, admission rules and visa steps. University names are examples, not endorsements.</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{countryGuides.map((guide) => <div key={guide.country} className="rounded-2xl border border-white/10 bg-[#0e1318] p-5"><h3 className="font-semibold">{guide.country}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{guide.universities}</p><div className="mt-5 flex gap-4 text-xs"><a href={guide.portal} target="_blank" rel="noreferrer" className="text-cyan-200 hover:text-white">Study portal ↗</a><a href={guide.visa} target="_blank" rel="noreferrer" className="text-slate-400 hover:text-white">Visa ↗</a></div></div>)}</div></section>
      <section id="help" className="mt-20 rounded-3xl border border-cyan-300/20 bg-cyan-300/5 p-7 sm:p-10"><div className="flex flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div><MessageCircle className="size-6 text-cyan-200" /><h2 className="mt-4 text-2xl font-semibold">Need a second pair of eyes?</h2><p className="mt-2 max-w-xl leading-7 text-slate-300">Send us the country, degree level, subject, GPA and target intake. We can help you make a shortlist and spot missing steps. Never send your passport, password, OTP or bank details.</p></div><div className="flex shrink-0 flex-col gap-3"><a href="https://www.facebook.com/" target="_blank" rel="noreferrer" className="rounded-xl bg-cyan-300 px-5 py-3 text-center text-sm font-semibold text-slate-950 hover:bg-cyan-200">Message on Facebook</a><a href="https://wa.me/" target="_blank" rel="noreferrer" className="rounded-xl border border-white/15 px-5 py-3 text-center text-sm font-medium text-white hover:bg-white/5">WhatsApp community</a></div></div></section>
      <p className="mt-8 text-xs leading-5 text-slate-600">Important: deadlines, eligibility, funding and immigration rules change. Verify the live call on the linked official source before applying. EarnLoop is an information service, not an immigration adviser, recruiter or legal representative.</p>
    </div>
  </main>;
}
