import type { JobPosting } from "@/lib/job-contract";

export function slugifyJobTitle(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

const E = "https://earnloop.app/";

export const seedJobPosts: JobPosting[] = [
  // ── Remote jobs ────────────────────────────────────────────────────────
  {
    id: "remote-customer-support-part-time",
    title: "Remote customer support agent (part-time)",
    company: "Small SaaS teams",
    category: "Remote jobs",
    location: "Remote · flexible hours",
    payBand: "Usually $4–12/hour, $0 to start",
    engagement: "Part-time contract",
    postedAt: "Rolling application",
    applyUrl: "https://supportremote.com/jobs",
    sourceLabel: "Remote support job feed",
    summary: "Support tickets for small software teams are often outsourced to individuals who can write clearly and stay calm under a queue. Start with one team, not five.",
    requirements: ["Clear written English in the team's timezone window", "A laptop, stable connection, and quiet workspace", "Calm, scripted responses for routine questions"],
    howItWorks: ["Apply with a 200-word reply to a sample ticket, not a generic CV.", "Start with a small weekly hour block and one queue.", "Ask for written feedback after your first ten tickets."],
    tags: ["support", "beginner", "no portfolio"],
    featured: true,
    seo: {},
  },
  {
    id: "appointment-setter-for-coaches",
    title: "Appointment setter for coaches and consultants",
    company: "Independent practitioners",
    category: "Remote jobs",
    location: "Remote · schedule by client timezone",
    payBand: "Often $5–15/hour plus per-booking bonus",
    engagement: "Per-client freelance",
    postedAt: "Rolling application",
    applyUrl: "https://www.remoteok.com/remote-appointment-setter-jobs",
    sourceLabel: "RemoteOK job board",
    summary: "Coaches book clients by filling calendars. A setter's job is to confirm interest, pick a slot, and relist a no-show — a narrow task people will pay for separately.",
    requirements: ["Comfort calling or messaging strangers politely", "Reliable calendar tooling and follow-up habits", "Ability to log notes a coach can trust"],
    howItWorks: ["Offer one paid trial week to one coach, not an open-ended search.", "Track scheduled, confirmed, and attended bookings per week.", "Charge per meeting set once your confirmation rate is visible."],
    tags: ["sales", "phone", "trial"],
    featured: false,
    seo: {},
  },
  {
    id: "junior-data-analyst-for-agencies",
    title: "Junior data analyst for marketing agencies",
    company: "Small agencies",
    category: "Remote jobs",
    location: "Remote",
    payBand: "$8–20/hour depending on tool depth",
    engagement: "Project or retainer",
    postedAt: "Rolling application",
    applyUrl: "https://www.flexjobs.com/remote-jobs/data-analysis",
    sourceLabel: "FlexJobs remote database",
    summary: "Agencies drown in dashboards. Someone who can pull raw export, clean it, and hand back a two-screen summary is worth more than the tools alone.",
    requirements: ["Comfort with spreadsheets beyond the basics", "One analytics platform you can defend (GA4, Looker Studio, or sheets)", "Honesty about what a metric does and doesn't show"],
    howItWorks: ["Rebuild one public agency dashboard as a free sample with labeled limits.", "Quote a fixed monthly audit window, not ongoing access.", "Ask for the raw data before promising insight."],
    tags: ["analytics", "spreadsheets", "intermediate"],
    featured: false,
    seo: {},
  },
  {
    id: "transcription-formatting-assistant",
    title: "Transcription formatting and clean-up assistant",
    company: "Podcast and course creators",
    category: "Remote jobs",
    location: "Remote · asynchronous",
    payBand: "$3–8/hour for clean-up work",
    engagement: "Per-episode contract",
    postedAt: "Rolling application",
    applyUrl: "https://www.peopleperhour.com/freelance-transcription-services",
    sourceLabel: "PeoplePerHour listings",
    summary: "Auto-transcription is fast but messy. Creators pay for a human pass that fixes names, timestamps, and speaker labels before publishing.",
    requirements: ["Fast typist with good spelling in the source language", "Patience with technical or accented speech", "Basic timestamp formatting sense"],
    howItWorks: ["Clean one free sample episode under 15 minutes.", "Quote a per-minute or per-episode rate.", "Deliver before deadline and keep the glossary of names updated."],
    tags: ["attention to detail", "beginner"],
    featured: false,
    seo: {},
  },
  // ── Virtual assistance ─────────────────────────────────────────────────
  {
    id: "general-va-for-one-person-agency",
    title: "General virtual assistant for a one-person agency",
    company: "Solo operators",
    category: "Virtual assistance",
    location: "Remote",
    payBand: "$3–10/hour with clear scope",
    engagement: "Monthly retainer",
    postedAt: "Rolling application",
    applyUrl: "https://www.belay.com/apply",
    sourceLabel: "Belay virtual assistant program",
    summary: "The first VA wins by owning a tiny operational loop — inbox triage, invoice chasing, or CRM hygiene — not by claiming to do everything.",
    requirements: ["One narrow task you can do blindly well", "Documented routines the client can read", "A weekly report of what moved and what waited"],
    howItWorks: ["Pitch a 1-hour daily task, not a 'full VA' package.", "Write your routine down so a replacement could run it.", "Raise scope only after two clean weeks on the same task."],
    tags: ["operations", "retainer", "beginner"],
    featured: true,
    seo: {},
  },
  {
    id: "travel-planning-va",
    title: "Travel planning VA for busy consultants",
    company: "Individual clients",
    category: "Virtual assistance",
    location: "Remote",
    payBand: "$5–12/hour or $30–60 per trip plan",
    engagement: "Per-trip project",
    postedAt: "Rolling application",
    applyUrl: "https://www.fiverr.com/",
    sourceLabel: "Fiverr travel-planning gigs",
    summary: "Executives pay to skip schedule-dense research: visa rules, stopover times, and refundable hotel comparisons they never have time to do.",
    requirements: ["Bookkeeping of visa and quarantine rules, clearly sourced", "Checklist discipline for documents and confirmations", "Comfort working across timezones"],
    howItWorks: ["Produce two sourced comparison tables as a sample.", "Quote a flat per-trip price with a revision cap.", "Always pin the official border rules your plan depends on."],
    tags: ["research", "sourcing", "intermediate"],
    featured: false,
    seo: {},
  },
  {
    id: "real-estate-admin-va",
    title: "Real-estate admin virtual assistant (listings and listings updates)",
    company: "Local brokerages",
    category: "Virtual assistance",
    location: "Remote · US timezone hours often needed",
    payBand: "$4–9/hour with MLS access",
    engagement: "Part-time contract",
    postedAt: "Rolling application",
    applyUrl: "https://www.zillow.com/",
    sourceLabel: "Real-estate team hiring pages",
    summary: "Brokers burn hours syncing listings across portals. A careful admin who keeps photos, prices, and statuses consistent is hired again and again.",
    requirements: ["Extreme consistency in data entry", "Willingness to learn portal-specific rules", "Discretion with client property details"],
    howItWorks: ["Demonstrate accuracy on a mock listing sync.", "Start with one broker's active-pipeline cleanup.", "Track your error rate per week and show improvement."],
    tags: ["admin", "data entry", "steady"],
    featured: false,
    seo: {},
  },
  {
    id: "podcast-scheduling-va",
    title: "Podcast guest-scheduling VA",
    company: "Hosts and bookers",
    category: "Virtual assistance",
    location: "Remote · asynchronous",
    payBand: "$3–7/hour or per booking",
    engagement: "Per-podcast contract",
    postedAt: "Rolling application",
    applyUrl: "https://podmatch.com/",
    sourceLabel: "PodMatch network",
    summary: "Guests confirm, reschedule, and ghost. A VA who keeps one booking calendar tidy and nudges no-shows saves a host a full day each week.",
    requirements: ["Friendly, persistent messaging style", "Calendar tooling fluency", "Reliable follow-up log"],
    howItWorks: ["Learn one host's booking workflow end to end.", "Own the confirm + remind + reschedule loop weekly.", "Report bookings won and no-shows reduced each month."],
    tags: ["calendar", "communication", "beginner"],
    featured: false,
    seo: {},
  },
  // ── Data entry & research ───────────────────────────────────────────────
  {
    id: "product-listing-data-entry",
    title: "Product listing data entry for ecommerce sellers",
    company: "Small stores",
    category: "Data entry & research",
    location: "Remote",
    payBand: "$3–8/hour or $0.10–0.30 per listing",
    engagement: "Per-listing or hourly",
    postedAt: "Rolling application",
    applyUrl: "https://www.upwork.com/",
    sourceLabel: "Upwork data-entry projects",
    summary: "Sellers need thousands of accurate listings: titles, specs, images, attributes. Speed matters, but consistency is what gets you rehired.",
    requirements: ["Typing speed plus a proofread pass on every row", "Following a style sheet without improvising", "Flagging ambiguous spec fields instead of guessing"],
    howItWorks: ["Offer a 20-row paid sample with source-provided specs.", "Quote a per-listing rate once you know the template.", "Maintain your own accuracy log per batch."],
    tags: ["ecommerce", "spreadsheets"],
    featured: false,
    seo: {},
  },
  {
    id: "market-research-collector",
    title: "Market research collector (public sources only)",
    company: "Founders and consultants",
    category: "Data entry & research",
    location: "Remote · asynchronous",
    payBand: "$4–10/hour for structured collection",
    engagement: "Per-project",
    postedAt: "Rolling application",
    applyUrl: "https://www.remotive.com/remote-jobs/data-entry",
    sourceLabel: "Remotive data jobs",
    summary: "Competitor pricing, review themes, and directory listings are tedious to collect and easy to miss. A collector who cites the source for every row is rare and valued.",
    requirements: ["Cite where every data point came from", "Follow a collection grid exactly", "Respect robots and licensing limits"],
    howItWorks: ["Deliver a 50-row test grid with sources.", "Scope by rows not hours so pricing is predictable.", "Flag anything you could not verify instead of padding cells."],
    tags: ["research", "citations", "intermediate"],
    featured: false,
    seo: {},
  },
  {
    id: "ai-data-labeling-gigs",
    title: "AI training-data annotation (category-by-category)",
    company: "Platform projects",
    category: "Data entry & research",
    location: "Remote",
    payBand: "$2–8/hour depending on task",
    engagement: "Per-task platform work",
    postedAt: "Rolling application",
    applyUrl: "https://www.scale.com/",
    sourceLabel: "Scale AI gig platform",
    summary: "Annotation tasks pay honestly for focus: judging similarity, labeling images, or rating responses. Treat it as a metered skill, not a career.",
    requirements: ["Attention to instruction details", "Consistency across batches", "Patience with slow, repetitive work"],
    howItWorks: ["Pass each qualification round with care.", "Do small batches and check your own error reports.", "Use the earning as proof of focus, then graduate to complex tasks."],
    tags: ["data", "qualification", "beginner"],
    featured: false,
    seo: {},
  },
  // ── Graphic & creative ──────────────────────────────────────────────────
  {
    id: "canva-template-refresh",
    title: "Canva template refresh for coaches and creators",
    company: "Solo brands",
    category: "Graphic & creative",
    location: "Remote",
    payBand: "$15–60 per template set",
    engagement: "Per-set project",
    postedAt: "Rolling application",
    applyUrl: "https://www.fiverr.com/",
    sourceLabel: "Fiverr design gigs",
    summary: "Most personal brands have messy templates. Refreshing a coach's existing Canva kit into clean, reusable frames is a narrow, well-paid first gig.",
    requirements: ["Working knowledge of Canva (frames, styles, brand kits)", "An eye for consistent spacing and type hierarchy", "Respecting license rules for any assets you use"],
    howItWorks: ["Re-design one free page from someone's real kit.", "Quote a fixed per-set price with a revision limit.", "Document the template rules so the client can self-serve."],
    tags: ["canva", "branding", "beginner"],
    featured: false,
    seo: {},
  },
  {
    id: "thumbnail-and-shorts-editing",
    title: "Thumbnail and shorts editing for small channels",
    company: "YouTubers and podcasters",
    category: "Graphic & creative",
    location: "Remote · asynchronous",
    payBand: "$3–12 per thumbnail",
    engagement: "Per-piece",
    postedAt: "Rolling application",
    applyUrl: "https://www.freelancer.com/",
    sourceLabel: "Freelancer design work",
    summary: "Channels test many thumbnails to find a clickable one. Fast, honest iterations beat one polished masterpiece.",
    requirements: ["Speed: three variants in a day, not one in a week", "Basic composition and color sense", "No fake engagement claims in your pitch"],
    howItWorks: ["Study CTR (click-through rate) language ethically before pitching.", "Deliver variants against the channel's own style.", "Ask which variant won and why."],
    tags: ["youtube", "iterations", "fast"],
    featured: false,
    seo: {},
  },
  {
    id: "ai-image-refinement",
    title: "AI image refinement and cleanup",
    company: "Founders and product teams",
    category: "Graphic & creative",
    location: "Remote",
    payBand: "$5–20/hour with a paid sample",
    engagement: "Per-project",
    postedAt: "Rolling application",
    applyUrl: "https://www.aigigz.com/",
    sourceLabel: "AI-gig marketplace",
    summary: "Generated images usually need a human pass: fixing hands, matching lighting, re-applying brand colors. That cleanup is a sellable reliability skill.",
    requirements: ["Prompt discipline plus editing tool fluency", "Honesty about what AI can't fix well", "Clean file delivery (no stray watermarks)"],
    howItWorks: ["Fix one client image as a timed sample.", "Charge by fixed outcome (per image or batch).", "Write the prompt recipe into your delivery notes."],
    tags: ["ai tools", "retouch", "intermediate"],
    featured: false,
    seo: {},
  },
  // ── Writing & proofreading ─────────────────────────────────────────────
  {
    id: "product-page-proofreader",
    title: "Product-page proofreader for small ecommerce stores",
    company: "Shop owners",
    category: "Writing & proofreading",
    location: "Remote",
    payBand: "$0.01–0.03 per word, 20–50 pages",
    engagement: "Per-page project",
    postedAt: "Rolling application",
    applyUrl: "https://www.reedsy.com/",
    sourceLabel: "Reedsy freelancer directory",
    summary: "A shop with typos loses trust at the checkout. Catching errors across hundreds of product pages is small, fast, and easy to price.",
    requirements: ["Strong spelling and grammar in the store's language", "A consistent style guide and change log", "Clear communication of what you did not change"],
    howItWorks: ["Proofread ten free pages and return a sample change log.", "Quote a flat per-page rate with a minimum batch.", "Deliver a summary of recurring errors the team can fix at the source."],
    tags: ["editing", "ecommerce", "beginner"],
    featured: true,
    seo: {},
  },
  {
    id: "local-business-email-copy",
    title: "Email copy for local service businesses",
    company: "Gyms, salons, contractors",
    category: "Writing & proofreading",
    location: "Remote",
    payBand: "$25–75 per email plus re-use rights",
    engagement: "Per-email project",
    postedAt: "Rolling application",
    applyUrl: "https://www.proz.com/",
    sourceLabel: "ProZ copywriting jobs",
    summary: "Local owners need a considered weekly email, not headline tricks. Simple, specific copy with one clear action is what actually books appointments.",
    requirements: ["Plain writing that sounds like a person", "One call-to-action per email, no sales gymnastics", "Harvesting real details from the business, not templates"],
    howItWorks: ["Rewrite one of their past emails free from their real offer.", "Quote per email and keep a one-interview word budget.", "Ask which subject line and action performed best."],
    tags: ["copy", "local", "intermediate"],
    featured: false,
    seo: {},
  },
  {
    id: "ghostwriting-trial-articles",
    title: "Long-form ghostwriting trial articles",
    company: "Founders and newsletters",
    category: "Writing & proofreading",
    location: "Remote",
    payBand: "$50–200 per finished article",
    engagement: "Per-article with potential retainer",
    postedAt: "Rolling application",
    applyUrl: "https://www.contently.com/",
    sourceLabel: "Contently network",
    summary: "Busy founders outsource essays and case studies. The deal is simple: keep their voice, cite the sources, never publish on your own feed.",
    requirements: ["An interview-to-draft workflow you can repeat", "Facts sourced and linked, opinions labeled", "Discretion and a clean ghostwriting agreement"],
    howItWorks: ["Offer a half-length paid sample on one real topic.", "Quote per article, not per hour, after one interview.", "Pitch a monthly retainer after three on-voice drafts."],
    tags: ["ghostwriting", "long-form", "intermediate"],
    featured: false,
    seo: {},
  },
  // ── Social media management ─────────────────────────────────────────────
  {
    id: "instagram-scheduler-local",
    title: "Instagram scheduler for local businesses",
    company: "Cafes, salons, shops",
    category: "Social media management",
    location: "Remote",
    payBand: "$3–8/hour or $150–400/month per account",
    engagement: "Monthly retainer",
    postedAt: "Rolling application",
    applyUrl: "https://www.indeed.com/",
    sourceLabel: "Indeed social media jobs",
    summary: "A cafe doesn't need a strategist; it needs someone to schedule real posts, answer the occasional comment, and show up weekly.",
    requirements: ["Scheduling tools and consistent posting discipline", "Using the business's real photos, never hotlinked stock", "A simple monthly report the owner can read"],
    howItWorks: ["Propose a 4-week posting grid before pricing.", "Start with one account and a fixed post count.", "Report reach and replies, and reprice before adding platforms."],
    tags: ["instagram", "retainer", "beginner"],
    featured: false,
    seo: {},
  },
  {
    id: "shorts-repurposing",
    title: "YouTube Shorts / Reels repurposing service",
    company: "Long-form creators",
    category: "Social media management",
    location: "Remote · asynchronous",
    payBand: "$10–40 per finished short",
    engagement: "Per-short contract",
    postedAt: "Rolling application",
    applyUrl: "https://www.workwithshorts.com/",
    sourceLabel: "Shorts creator marketplace",
    summary: "Long videos hide 3–5 clips worth sharing. Repurposing means finding the moment, captioning it honestly, and keeping the creator's voice intact.",
    requirements: ["Mean to find a real payoff moment in long footage", "Legible captions and honest highlight framing", "Timing and raw footage hygiene"],
    howItWorks: ["Send one repurposed clip from a creator's public video.", "Price per short, offer a 3-clip trial pack.", "Reprice when edits require the creator's direction loops."],
    tags: ["video", "repurposing", "intermediate"],
    featured: false,
    seo: {},
  },
  {
    id: "community-moderation-retainer",
    title: "Community moderation for niche Discord and Facebook groups",
    company: "Founders and communities",
    category: "Social media management",
    location: "Remote",
    payBand: "$3–7/hour with a posted policy",
    engagement: "Weekly retainer",
    postedAt: "Rolling application",
    applyUrl: "https://www.cmgrants.com/",
    sourceLabel: "Community-manager job feeds",
    summary: "Niche groups die from spam and flameouts. A calm moderator who moves threads, welcomes members, and logs escalations keeps a community alive.",
    requirements: ["Policy-first judgment, never drama-first", "Consistent hours and a visible on-call rota", "A weekly escalation log for the owner"],
    howItWorks: ["Shadow-mod one week with a written code of conduct.", "Own off-hours coverage and the welcome loop.", "Report incidents and policy gaps, not just churn."],
    tags: ["community", "policy", "beginner"],
    featured: false,
    seo: {},
  },
  // ── Side hustles & tips ─────────────────────────────────────────────────
  {
    id: "printable-planners-loop",
    title: "Printable planners and study kits: first-dollar loop",
    company: "Your own store",
    category: "Side hustles & tips",
    location: "Anywhere",
    payBand: "First $1 within days; PDF margins ~60–80%",
    engagement: "Own product · Canva + storefront",
    postedAt: "Updated with the blueprint",
    applyUrl: E,
    sourceLabel: "EarnLoop blueprint",
    summary: "Design a focused study or planner PDF with tools you already have, list it on a storefront, and collect the first proof before optimizing anything.",
    requirements: ["A niche you can research (exam, field, season)", "One afternoon to design a genuinely useful layout", "Patience to gather honest reviews"],
    howItWorks: ["Follow the full EarnLoop launch checklist for a planner.", "Ship one useful SKU, not twenty rushed ones.", "Improve from reviewer requests, then price the next batch."],
    tags: ["print-on-demand", "own product", "first dollar"],
    featured: true,
    seo: {},
  },
  {
    id: "local-service-flyer-loop",
    title: "Local service flyer loop: listings to appointments",
    company: "Close-by buyers",
    category: "Side hustles & tips",
    location: "Local + phone",
    payBand: "$15–40 per lead for tradies and tutors",
    engagement: "Own outreach",
    postedAt: "Updated with the blueprint",
    applyUrl: E,
    sourceLabel: "EarnLoop blueprint",
    summary: "Find a visible local need, post a tight offer in the places those buyers already look, and close the first small appointment on the phone.",
    requirements: ["Choose one service with an obvious pain point", "A flyer and a script, both deliberately short", "Discipline to follow up within 24 hours"],
    howItWorks: ["List three places your buyer already searches today.", "Post a specific offer with a price anchor, not a pitch.", "Close calls with a yes/no question and a booked slot."],
    tags: ["local", "leads", "beginner"],
    featured: false,
    seo: {},
  },
  // ── Online earning ideas ────────────────────────────────────────────────
  {
    id: "micro-consulting-skill",
    title: "Micro-consulting: sell a 30-minute session, not a package",
    company: "Your existing skill",
    category: "Online earning ideas",
    location: "Remote · via video",
    payBand: "$15–75 per focused session",
    engagement: "Per-session",
    postedAt: "Rolling application",
    applyUrl: E,
    sourceLabel: "EarnLoop blueprint",
    summary: "People pay for a specific answer, not an endless engagement. A 30-minute session on one problem is the cheapest honest way to test demand.",
    requirements: ["One skill where you genuinely know the answer", "A clear session outline and a 'what you won't cover' line", "A way to collect a question before payment"],
    howItWorks: ["List a fixed session price with a strict scope line.", "Collect the question in the booking form, not on the call.", "Record (with permission) what changed afterward as proof."],
    tags: ["consulting", "services", "beginner"],
    featured: false,
    seo: {},
  },
  {
    id: "digital-tool-teardown",
    title: "Digital tool teardowns: short how-to notes people pay for",
    company: "Your own notes",
    category: "Online earning ideas",
    location: "Anywhere",
    payBand: "Free or $5–15 per teardown",
    engagement: "Own content",
    postedAt: "Rolling application",
    applyUrl: E,
    sourceLabel: "EarnLoop prompt library",
    summary: "Take one tool people actually use, document its honest limits, and publish a walkthrough. Useful teardowns gather searches others skip.",
    requirements: ["A tool you have genuinely worked with", "Screenshots and captions from your own account", "Honest 'here's where it fails' sections"],
    howItWorks: ["Pick a tool with a search intent you can name.", "Publish one teardown a week from the prompt templates.", "Reply to the comments; the questions are your next topics."],
    tags: ["content", "seo", "own product"],
    featured: false,
    seo: {},
  },
  {
    id: "course-notes-and-summaries",
    title: "Course notes and summarized study guides",
    company: "Your own study work",
    category: "Online earning ideas",
    location: "Anywhere",
    payBand: "$2–15 per guide",
    engagement: "Own product",
    postedAt: "Rolling application",
    applyUrl: E,
    sourceLabel: "EarnLoop prompt library",
    summary: "Summarize material you are already learning into a clean, sourced study guide. The work is real, the format is cheap, and the audience searches by topic.",
    requirements: ["Material you actually studied", "Careful citing of original sources", "No 'pass without study' claims — ever"],
    howItWorks: ["Turn one finished course module into a study guide.", "Price it low and collect one genuine review.", "Add a new guide each time you finish a module."],
    tags: ["education", "guides", "beginner"],
    featured: false,
    seo: {},
  },
];

export const seedJobCategories: string[] = [
  "Remote jobs",
  "Virtual assistance",
  "Data entry & research",
  "Graphic & creative",
  "Writing & proofreading",
  "Social media management",
  "Side hustles & tips",
  "Online earning ideas",
];

export function getSeedJobPosting(id: string): JobPosting | undefined {
  return seedJobPosts.find((job) => job.id === id);
}
