export type PromptCategory = "Build" | "Visuals" | "Education" | "Play";
export type Prompt = { title: string; category: PromptCategory; tool: string; summary: string; prompt: string };
export const prompts: Prompt[] = [
  { title: "Ship a responsive landing page", category: "Build", tool: "ChatGPT / Gemini / Claude", summary: "Turn a product brief into an accessible implementation plan.", prompt: "Act as a senior product engineer. Build a responsive landing page for [product] using [stack]. Define the structure, states and data shape first. Then provide accessible, mobile-first code with keyboard focus states, loading/error states and a test checklist. Do not invent APIs; mark integration points." },
  { title: "Debug without guessing", category: "Build", tool: "ChatGPT / Claude", summary: "Create a reproducible debugging loop instead of a speculative patch.", prompt: "You are debugging [error]. Here is the smallest reproduction: [code/log]. Ask only the essential missing question, identify the likely root cause, explain why, propose the smallest safe fix and provide a regression test. Separate facts from hypotheses." },
  { title: "Editorial portrait direction", category: "Visuals", tool: "Image model", summary: "Style a portrait while preserving identity and natural detail.", prompt: "Transform this reference into a refined editorial portrait: [style]. Preserve identity, facial proportions, skin texture, age and expression. Use [lighting], [palette], [lens/composition] and a clean background. Avoid plastic skin, extra fingers, text, logos and distorted anatomy." },
  { title: "Product photo style matrix", category: "Visuals", tool: "Image model", summary: "Generate consistent visual variants for a shop or campaign.", prompt: "Create 6 consistent product-photo directions for [product]. Keep shape, branding and colors accurate. Vary only the setting: [settings]. For each specify lighting, surface, camera angle, negative prompts and a reusable style note." },
  { title: "Teach a hard idea simply", category: "Education", tool: "ChatGPT / Gemini", summary: "Design a student-friendly lesson with checks for understanding.", prompt: "Teach [concept] to a [level] student who knows [prerequisite]. Use an analogy, visual explanation in words, worked example, three misconceptions, five questions from easy to challenging and an answer key. Show the reasoning." },
  { title: "Study plan from a syllabus", category: "Education", tool: "ChatGPT / Gemini", summary: "Turn a syllabus and available time into a realistic learning loop.", prompt: "Create a [weeks]-week study plan for [subject] using this syllabus: [paste]. I have [hours] per week and my assessment is [date/type]. Schedule retrieval, spaced review, projects and rest. Define weekly deliverables and a diagnostic checkpoint." },
  { title: "Invent a useful party game", category: "Play", tool: "ChatGPT", summary: "Make an inclusive game with a quick prototype path.", prompt: "Invent a 10-minute party game for [people] using only [materials]. It should be easy to explain, funny without targeting protected traits, replayable and accessible. Give objective, setup, turns, win condition, example round and balancing variants." },
];
