export type Prompt = { title: string; category: string; tool: string; summary: string; prompt: string };
export const prompts: Prompt[] = [
  // ── Build ──────────────────────────────────────────────────────────────
  { title: "Ship a responsive landing page", category: "Build", tool: "ChatGPT / Gemini / Claude", summary: "Turn a product brief into an accessible implementation plan.", prompt: "Act as a senior product engineer. Build a responsive landing page for [product] using [stack]. Define the structure, states and data shape first. Then provide accessible, mobile-first code with keyboard focus states, loading/error states and a test checklist. Do not invent APIs; mark integration points." },
  { title: "Debug without guessing", category: "Build", tool: "ChatGPT / Claude", summary: "Create a reproducible debugging loop instead of a speculative patch.", prompt: "You are debugging [error]. Here is the smallest reproduction: [code/log]. Ask only the essential missing question, identify the likely root cause, explain why, propose the smallest safe fix and provide a regression test. Separate facts from hypotheses." },
  { title: "Turn a scope into a build checklist", category: "Build", tool: "ChatGPT / Gemini / Claude", summary: "Break a brief into shippable milestones with definitions of done.", prompt: "Act as a product engineer. Turn this brief into a build checklist: [brief]. Return ordered milestones with a Definition of Done per milestone, the smallest end-to-end slice first, the tests to include, and what to postpone. Flag every assumption that could change scope." },
  { title: "Architect a tiny SaaS MVP", category: "Build", tool: "ChatGPT / Gemini / Claude", summary: "Sketch a lean architecture and spell out what to cut for launch.", prompt: "You are a pragmatic architect. Sketch the architecture for a [purpose] SaaS MVP that must serve [users] on a [budget]. Use my stack [stack]. Give the module breakdown, an ASCII data-flow diagram, the auth approach, a cost estimate, and explicitly the features to leave out until after launch." },
  { title: "Design a Postgres schema from a product brief", category: "Build", tool: "ChatGPT / Claude", summary: "Turn a product brief into a schema you can apply directly.", prompt: "Act as a database designer. Design a Postgres schema for [product brief]. Return tables with columns, types and keys, plus one realistic insert per table. Add row-level-security notes if the app has multi-tenant data, and flag columns you would index from day one." },
  { title: "Turn an API spec into typed client code", category: "Build", tool: "ChatGPT / Claude", summary: "Generate typed SDK code straight from an API description.", prompt: "Turn this API description into typed client code for [language/framework]: [spec]. Generate request/response types, an HTTP client, error handling and three usage examples with edge cases. If I provide project conventions, follow them: [code]." },
  { title: "Audit your page for accessibility", category: "Build", tool: "ChatGPT / Gemini / Claude", summary: "Find real a11y failures and get code-level fixes, not advice.", prompt: "Act as an accessibility specialist. Audit this page: [code or description]. Check landmarks, heading order, focus states, contrast, form labels and touch targets. Return a priority-sorted fix list with code-level changes, not general advice." },
  { title: "Plan a performance budget", category: "Build", tool: "ChatGPT / Claude", summary: "Set a budget and a measurable optimization order.", prompt: "Create a performance plan for [page/app]. Define a budget (LCP, CLS, INP, transfer size) for [device], identify the likely bottlenecks for [stack], and give an ordered plan with before/after measurement steps. Only include changes with a measurable win." },
  { title: "Write end-to-end tests for one critical flow", category: "Build", tool: "ChatGPT / Claude", summary: "Cover the happy path, validation, and failure cases deterministically.", prompt: "Write end-to-end tests for the critical flow '[flow]' of this app: [context/code]. Cover the happy path, validation errors, network failures and auth. Structure tests readably, mark any waits that need explicit handling, and keep assertions specific." },
  { title: "Write API docs users can ship from", category: "Build", tool: "ChatGPT / Gemini / Claude", summary: "Turn an endpoint list into docs a stranger can use in five minutes.", prompt: "Turn this API into user-facing docs: [spec/endpoints]. Use real request/response examples, mark auth steps and rate limits, add a quick-start that works in five minutes, and list common errors. Write for a developer who has never seen the codebase." },
  { title: "Automate a repetitive task", category: "Build", tool: "ChatGPT / Gemini / Claude", summary: "Design a small script that replaces a manual workflow safely.", prompt: "Design a small script to replace this manual workflow: [task, inputs, outputs]. Recommend language/library choices, outline the steps with failure handling, estimate runtime, and include logging so the automation is auditable." },
  { title: "Add secure auth without overengineering", category: "Build", tool: "ChatGPT / Claude", summary: "Pick the simplest secure auth and list the must-dos.", prompt: "Design the auth for a [type] app on [stack]. Recommend the simplest secure option (session vs JWT, social vs email, where row-level security fits), list the security must-dos (password rules, rate limiting, session expiry, audit log), then the exact steps to implement it." },

  // ── Earn ───────────────────────────────────────────────────────────────
  { title: "Validate a niche with a landing test", category: "Earn", tool: "ChatGPT / Gemini", summary: "Design a one-page test that produces demand signal in two weeks.", prompt: "Act as a product strategist. I believe [niche] will pay for [outcome]. Design a one-page landing test: headline promise, one offer, a CTA and three objections addressed. Give a 14-day plan with daily actions, the minimum sign-up count that signals demand, and which metric to treat as the real signal." },
  { title: "Price your first package", category: "Earn", tool: "ChatGPT / Claude", summary: "Set a value-based price with three levels and one test.", prompt: "You are a pricing consultant. For my service [service + outcomes + hours], design a value-based price. Walk through anchoring on the outcome's value to the buyer, your cost floor, three package levels with names, and one yes/no pricing test to run. Be honest about the evidence I still lack." },
  { title: "Write a one-line offer", category: "Earn", tool: "ChatGPT / Gemini / Claude", summary: "Compress an idea into a clear problem-to-result offer.", prompt: "Act as a direct-response copywriter. Turn the raw idea 'I help [audience] with [service] to get [outcome]' into a one-line offer using a problem-to-mechanism-to-result structure with proof. Give five options ordered from safe to punchy." },
  { title: "Cold outreach that gets replies", category: "Earn", tool: "ChatGPT / Claude", summary: "A four-sentence outreach email people actually answer.", prompt: "Act as a cold email expert. Draft a four-sentence outreach email to [persona] offering [specific outcome]. No fake flattery, mention one specific detail I will insert, include one small proof point, and end with a low-friction question. Give three subject lines." },
  { title: "Run a discovery call like a pro", category: "Earn", tool: "ChatGPT / Gemini / Claude", summary: "A discovery script that separates real buyers from tire-kickers.", prompt: "You are a sales coach. Write a discovery-call script for my offer [offer]. Sequence: context, pain, budget and impact, current solution, why now, next step. Include the questions to ask, which answers signal a real buyer, and the exact language to close for a paid pilot." },
  { title: "Turn a skill into an audit template", category: "Earn", tool: "ChatGPT / Gemini", summary: "Package a skill as a 60-minute paid diagnostic.", prompt: "Turn my skill [skill] into a sellable 60-minute audit. Define the deliverables the client receives, the questions that diagnose [problem], the scorecard, and a three-part written recommendation. Include the pricing logic and how to offer the fix afterward." },
  { title: "Freelance proposal that closes", category: "Earn", tool: "ChatGPT / Claude", summary: "A one-page proposal with scope, timeline and a clear next step.", prompt: "Act as a proposal writer. Draft a proposal for [project] to [client type]: restate the problem in their words, show my specific approach, the timeline, a [$X] fee with scope guardrails, and the next step. Keep it under one page, concrete, and free of buzzwords." },
  { title: "Write your digital product listing", category: "Earn", tool: "ChatGPT / Gemini / Claude", summary: "Turn a product into a store listing that sells without hype.", prompt: "Turn my product into a store listing: [product, format, price]. Write a 90-word headline, a scannable description (benefits first, features second), bullet points, an FAQ, and a refund line that reduces risk. Match the tone of [comparison store]." },
  { title: "Plan your first $1 proof", category: "Earn", tool: "ChatGPT / Gemini", summary: "A week-by-week path to your first real payment.", prompt: "Design the fastest path to my first $1 of revenue for [product/service/audience]. Give the smallest sellable unit, the smallest possible buyer list, the channel to reach them this week, the exact ask, and what the payment proof unlocks next. Ban validation that does not collect money." },
  { title: "Map an affiliate pathway", category: "Earn", tool: "ChatGPT / Gemini / Claude", summary: "Find affiliate products worth testing for your audience.", prompt: "Find an affiliate path for [niche]. List products I could promote to [audience], realistic commission ranges, the matching content format for each, and expected conversion reality rather than hype. Flag compliance notes for my market and give three first posts to test." },
  { title: "Craft a local services offer", category: "Earn", tool: "ChatGPT / Gemini / Claude", summary: "Package your skill for local businesses you can walk into.", prompt: "Act as a local marketing specialist. Create a service offer for [local business type] that uses [my skill]. Include an irresistible first-visit offer, a one-line pitch for walking in, a flyer script, and measurable follow-up so I know if it worked." },

  // ── Marketing ──────────────────────────────────────────────────────────
  { title: "Build an SEO content cluster", category: "Marketing", tool: "ChatGPT / Claude", summary: "A pillar-and-support plan that builds topical authority fast.", prompt: "Act as an SEO strategist. Build a content cluster for the seed topic '[topic]'. Give the pillar page angle, eight supporting articles, the internal-link plan, target keywords with realistic difficulty notes, and the order to publish for fastest topical authority." },
  { title: "Write meta titles that get clicks", category: "Marketing", tool: "ChatGPT / Gemini / Claude", summary: "Ten title and description pairs with a real benefit each.", prompt: "Write ten title and meta-description pairs for [page topic/purpose]. Titles under 60 characters with a concrete benefit; descriptions under 155 characters stating the promise and the proof. Mix formats: question, number, how-to, and outcome." },
  { title: "Launch in a community without spamming", category: "Marketing", tool: "ChatGPT / Claude", summary: "A respectful launch plan that fits a community's norms.", prompt: "Plan a respectful launch in [community] for my [product]. Give how to check the rules and existing posts, a genuinely useful contribution strategy for two weeks before launch, the launch-post angle, and how to handle criticism. No mass DMs." },
  { title: "Script a short-form video", category: "Marketing", tool: "ChatGPT / Gemini / Claude", summary: "A 45-second script with a hook and on-screen text.", prompt: "Write a 45-second vertical video script for [goal]. Structure: a two-second hook that is specific rather than vague, the problem, one surprising insight, the payoff, and a CTA. Provide the on-screen text for each beat and a caption optimized for shares." },
  { title: "Welcome email sequence", category: "Marketing", tool: "ChatGPT / Gemini / Claude", summary: "Four emails that deliver, teach, sell, and ask.", prompt: "Write a four-email welcome sequence for [lead magnet/subscription]. Email 1 delivers value and sets a promise, 2 teaches, 3 presents the offer gently, 4 asks for a response. Each under 150 words with a subject line and a single CTA." },
  { title: "Campaign brief for paid ads", category: "Marketing", tool: "ChatGPT / Claude", summary: "Angles, creatives, budgets, and the metrics that decide.", prompt: "Act as a media buyer. Write a campaign brief for [offer] targeting [audience] on [platform]. Give budget bands, three ad angles (pain, social proof, and a non-urgency approach), matching creatives, the landing page requirement, and the metrics that justify scaling or cutting." },
  { title: "Repurpose one asset into ten", category: "Marketing", tool: "ChatGPT / Gemini / Claude", summary: "Turn one good piece of content into a content system.", prompt: "Take '[asset]' and map a repurposing plan: a LinkedIn post, a thread, an email, a short video script, a carousel, three tweet ideas, a newsletter blurb, and an SEO article angle. Each points back to the original with a specific hook." },
  { title: "Keyword brief from a seed word", category: "Marketing", tool: "ChatGPT / Claude", summary: "Group real search intent into content angles.", prompt: "Generate a keyword brief from the seed '[seed]'. Output fifteen keywords grouped by intent (informational, commercial, transactional), realistic search-demand ranges, and one content angle per group that matches what a real buyer needs." },
  { title: "Launch-day checklist for a product", category: "Marketing", tool: "ChatGPT / Gemini / Claude", summary: "A one-day sequence plus a week of follow-up.", prompt: "Build a one-day launch checklist for [product] to [audience] on [channel]. Sequence the announcements hour by hour, list who to notify and what asset each needs, and include one clear win metric for the day plus a follow-up plan for the week." },
  { title: "Ask customers for proof", category: "Marketing", tool: "ChatGPT / Claude", summary: "Short, personal asks that collect testimonials and referrals.", prompt: "Write the messages I can send to [number] happy customers to collect proof. Include a check-in with no strings, a specific testimonial ask (what to include), a review-site ask, and a referral ask. Short, personal, and free of incentive spam." },
  { title: "LinkedIn post that sparks replies", category: "Marketing", tool: "ChatGPT / Claude", summary: "Under 120 words with a question that invites specific answers.", prompt: "Write a LinkedIn post for [professional persona] about [lesson/outcome]. Open with a specific conflict or result, keep it under 120 words, and end with one question that invites specific replies. No hashtag salad and no fake modesty. Give three headline variants." },

  // ── Writing ────────────────────────────────────────────────────────────
  { title: "Turn an outline into a first draft", category: "Writing", tool: "ChatGPT / Gemini / Claude", summary: "A complete draft that matches a reference voice.", prompt: "Write the first draft of a [type] piece using this outline: [outline]. Match the tone of [reference] and aim for [word count]. Use concrete details over adjectives, one idea per paragraph, and end with one decision or action for the reader." },
  { title: "Rewrite a draft for clarity", category: "Writing", tool: "ChatGPT / Claude", summary: "Cut jargon and make the main point land in two lines.", prompt: "Rewrite this draft for clarity: [draft]. Cut or explain jargon, shorten sentences, keep the strongest example, and make the main point land in the first two lines. Show three before/after sentence pairs so I learn the pattern." },
  { title: "Tighten your writing", category: "Writing", tool: "ChatGPT / Gemini / Claude", summary: "Cut 30% without losing the author's voice.", prompt: "Edit this text to be 30% shorter without losing meaning or voice: [text]. Keep the personality, remove filler, and flag anywhere the cut hurt clarity. Return a short before/after note per paragraph." },
  { title: "Newsletter from raw notes", category: "Writing", tool: "ChatGPT / Gemini / Claude", summary: "Scattered notes become a readable issue with one CTA.", prompt: "Turn these raw notes into a newsletter issue: [notes]. Structure: a strong opener explaining why now, three scannable sections, one personal anecdote, and a single CTA. Under 400 words, plus a subject line and preview text." },
  { title: "Case study that sells", category: "Writing", tool: "ChatGPT / Claude", summary: "A template that turns a customer story into proof.", prompt: "Write a case-study template for my [product/service] based on this story: [outcome/comments]. Structure: the customer's problem, what they tried before, the fix, a measurable result with numbers, and a quote-ready testimonial. Keep it under 400 words." },
  { title: "FAQ that handles objections", category: "Writing", tool: "ChatGPT / Gemini / Claude", summary: "Answers that reduce risk and surface real readiness.", prompt: "Write an FAQ for [offer/audience] covering these objections: [objections]. Each answer acknowledges the worry, gives one specific fact or guarantee, and restates the easy next step. Then add three yes/no questions that signal a ready buyer and three that mean not yet." },
  { title: "Sales page sections", category: "Writing", tool: "ChatGPT / Claude", summary: "The full section stack for a non-hype sales page.", prompt: "Act as a conversion copywriter. Write the sections for a sales page selling [offer] to [audience]: headline and subhead, the problem story, the mechanism (how it works), proof, objections, offer and guarantee, FAQ, and the final CTA. Keep the tone specific and non-hype." },
  { title: "Video script with a hook", category: "Writing", tool: "ChatGPT / Gemini / Claude", summary: "A script whose first three seconds earns the watch.", prompt: "Write a [length]-second video script for [topic/goal]. The first three seconds are the hook: a counterintuitive or concrete statement. Then setup, an explanation with one example, and the ask. Include visual directions in brackets." },
  { title: "Turn notes into a thread", category: "Writing", tool: "ChatGPT / Claude", summary: "Substance-first thread from raw notes.", prompt: "Turn these notes into a thread: [notes]. The first tweet makes a strong claim with a payoff; each following tweet adds one idea; the last offers the artifact. Give three alternative first tweets. Nothing engagement-bait: substance first." },

  // ── Visuals ────────────────────────────────────────────────────────────
  { title: "Editorial portrait direction", category: "Visuals", tool: "Image model", summary: "Style a portrait while preserving identity and natural detail.", prompt: "Transform this reference into a refined editorial portrait: [style]. Preserve identity, facial proportions, skin texture, age and expression. Use [lighting], [palette], [lens/composition] and a clean background. Avoid plastic skin, extra fingers, text, logos and distorted anatomy." },
  { title: "Product photo style matrix", category: "Visuals", tool: "Image model", summary: "Generate consistent visual variants for a shop or campaign.", prompt: "Create 6 consistent product-photo directions for [product]. Keep shape, branding and colors accurate. Vary only the setting: [settings]. For each specify lighting, surface, camera angle, negative prompts and a reusable style note." },
  { title: "Back a brand kit", category: "Visuals", tool: "Image model / ChatGPT", summary: "Fonts, colors, and mood that fit the audience, with reasoning.", prompt: "Act as a brand designer. From this brief [product/audience/feel], propose a brand kit: three font pairings, a five-color palette with hexes and usage ratios, a voice-and-mood board in words, and three logo-direction adjectives. Explain why each choice fits the audience." },
  { title: "Logo concepts from a brief", category: "Visuals", tool: "Image model", summary: "Four logo directions that still read at small sizes.", prompt: "Generate four logo concepts for [name/business] that communicates [idea]. Vary the approach: typographic, symbol, monogram, and emblem. For each, describe the shape language, why it reads correctly, and where it would break at small sizes." },
  { title: "Ad creative variants", category: "Visuals", tool: "Image model", summary: "Three feed-and-story creatives for one offer.", prompt: "Create three ad creative directions for [offer/audience]: one photo-based, one clean product shot, and one bold typographic. Specify composition, copy overlay, and the CTA button text per variant, sized for both feed and story placements." },
  { title: "Thumbnail design brief", category: "Visuals", tool: "Image model", summary: "Composition, contrast, and one keyword for click-through.", prompt: "Design a thumbnail for [topic] targeting [audience]. Describe the composition, the focal element, one keyword to display, the contrast strategy for small sizes, and two emotional alternatives: curiosity and clarity." },
  { title: "Infographic from a dataset", category: "Visuals", tool: "Image model / ChatGPT", summary: "Turn data into a three-number story with chart choices.", prompt: "Turn this dataset into an infographic plan for [audience]: [data]. Pick the three most persuasive numbers, the chart types that fit, the visual hierarchy, and a headline. Describe the layout so a designer can execute it without further input." },
  { title: "Before/after transformation", category: "Visuals", tool: "Image model", summary: "Consistent framing that makes the difference obvious and honest.", prompt: "Plan a before/after visual for [transformation], with consistent framing, lighting, and angle notes so the difference is obvious and believable. Include a capture checklist and a guard against over-editing." },

  // ── Education ──────────────────────────────────────────────────────────
  { title: "Teach a hard idea simply", category: "Education", tool: "ChatGPT / Gemini", summary: "Design a student-friendly lesson with checks for understanding.", prompt: "Teach [concept] to a [level] student who knows [prerequisite]. Use an analogy, a visual explanation in words, a worked example, three misconceptions, five questions from easy to challenging and an answer key. Show the reasoning." },
  { title: "Study plan from a syllabus", category: "Education", tool: "ChatGPT / Gemini", summary: "Turn a syllabus and available time into a realistic learning loop.", prompt: "Create a [weeks]-week study plan for [subject] using this syllabus: [paste]. I have [hours] per week and my assessment is [date/type]. Schedule retrieval, spaced review, projects and rest. Define weekly deliverables and a diagnostic checkpoint." },
  { title: "Course outline from a skill", category: "Education", tool: "ChatGPT / Claude", summary: "Package a skill into a course of five tight modules.", prompt: "Turn my skill [skill] into a [length]-hour course outline. Define the student's start and end capability, five modules with titles and outcomes, exercises per module that produce a portfolio artifact, and what I must NOT include to keep scope small." },
  { title: "Quiz generator from your content", category: "Education", tool: "ChatGPT / Gemini / Claude", summary: "A ten-question quiz with feedback for every wrong answer.", prompt: "From this content [notes/video], generate a ten-question quiz: two recall, three application, two analysis, two scenario, and one synthesis. Give each question a short feedback line so the learner learns from wrong answers." },
  { title: "Explainer video script", category: "Education", tool: "ChatGPT / Gemini", summary: "A 90-second script that makes the concept click.", prompt: "Write a 90-second explainer script for [concept/feature] to [audience]. Go problem, how it works, the moment it clicks, next step. Use one concrete everyday analogy and specify the animation notes in brackets." },
  { title: "Facilitator guide for a workshop", category: "Education", tool: "ChatGPT / Gemini / Claude", summary: "A 60-minute workshop with stuck-point handling.", prompt: "Design a 60-minute small-group workshop on [topic]. Give the agenda with time blocks, one energizing opener, the group exercise with instructions, likely stuck-points and how to unstick, and a closing that produces immediate next actions." },
  { title: "Learner stuck diagnostic", category: "Education", tool: "ChatGPT / Gemini", summary: "Find whether it is a gap, a misconception, or motivation.", prompt: "Act as a tutor. A student learning [topic] is stuck on [specific]. List the three most likely causes (prerequisite gap, misconception, motivation), a two-minute diagnosis for each, and the corrective exercise for each cause." },

  // ── Play ───────────────────────────────────────────────────────────────
  { title: "Invent a useful party game", category: "Play", tool: "ChatGPT", summary: "Make an inclusive game with a quick prototype path.", prompt: "Invent a 10-minute party game for [people] using only [materials]. It should be easy to explain, funny without targeting protected traits, replayable and accessible. Give objective, setup, turns, win condition, example round and balancing variants." },
  { title: "Trivia night from one topic", category: "Play", tool: "ChatGPT / Gemini", summary: "A friendly round that keeps the least-knowledgeable player in.", prompt: "Create a trivia round on [topic] for [group size]. Ten questions across easy, medium, and hard with answers and one fun fact each. Include a rapid-fire tiebreaker and a way to keep it friendly for the person who knows the least." },
  { title: "Family challenge pack", category: "Play", tool: "ChatGPT", summary: "Five challenges all ages can join.", prompt: "Invent five family challenges using [materials/time]. For each: a silly-but-doable goal, setup, win condition, and a way for all ages to participate. Order them from quiet to energetic." },
  { title: "Improv warm-up generator", category: "Play", tool: "ChatGPT", summary: "Six quick warm-ups that train one skill each.", prompt: "Generate six improv warm-ups for [group size/experience] that each build a specific skill: listening, accepting, or adding detail. Each under five minutes with simple instructions and one debrief question." },
];