export type RouteType = "Scholarship" | "Study portal" | "Work route";

export type Opportunity = {
  name: string;
  country: string;
  type: RouteType;
  level: string;
  funding: string;
  summary: string;
  eligibility: string;
  howToApply: string;
  source: string;
  sourceLabel: string;
  documents?: string[];
  steps?: string[];
};

export const opportunities: Opportunity[] = [
  { name: "Erasmus Mundus Joint Masters", country: "Europe", type: "Scholarship", level: "Master's", funding: "Full scholarship may cover tuition, travel and living", summary: "Competitive joint master's degrees delivered by a consortium of European universities.", eligibility: "Students worldwide; requirements vary by programme.", howToApply: "Choose a programme from the catalogue, read its consortium page and apply directly before that programme's deadline.", source: "https://www.eacea.ec.europa.eu/scholarships/emjm-catalogue_en", sourceLabel: "European Commission catalogue" },
  { name: "Chevening Scholarships", country: "United Kingdom", type: "Scholarship", level: "Master's", funding: "Fully funded UK one-year master's", summary: "The UK government's global scholarship for future leaders.", eligibility: "Work experience and leadership evidence are required; check the annual call for country details.", howToApply: "Create an account on the official Chevening application portal and submit the form and references during the open cycle.", source: "https://www.chevening.org/scholarships/", sourceLabel: "UK Foreign, Commonwealth & Development Office" },
  { name: "Australia Awards Scholarships", country: "Australia", type: "Scholarship", level: "Undergraduate / Master's", funding: "Tuition, return travel, living and health cover may be included", summary: "Long-term development scholarships for citizens of participating countries.", eligibility: "Participating-country rules apply; Bangladesh and India availability can change by intake.", howToApply: "Select your country on the official site, read the country profile and use its application instructions.", source: "https://www.dfat.gov.au/people-to-people/australia-awards", sourceLabel: "Australian Department of Foreign Affairs and Trade" },
  { name: "MEXT Scholarship", country: "Japan", type: "Scholarship", level: "Undergraduate / Master's / PhD", funding: "Government scholarship with stipend and tuition support", summary: "Japanese government awards offered through embassy recommendation or university recommendation.", eligibility: "Age, academic and language requirements vary by category and embassy.", howToApply: "Follow the MEXT notice published by the Japanese Embassy in your country or the university recommendation route.", source: "https://www.studyinjapan.go.jp/en/planning/scholarships/mext-scholarships/", sourceLabel: "Study in Japan (JASSO)" },
  { name: "Stipendium Hungaricum", country: "Hungary", type: "Scholarship", level: "Bachelor's / Master's / PhD", funding: "Tuition-free education, stipend and accommodation contribution", summary: "Hungary's international higher-education scholarship programme.", eligibility: "Sending-partner nomination and programme-specific requirements apply.", howToApply: "Apply through the online Tempus Public Foundation system and follow your sending partner's nomination process.", source: "https://stipendiumhungaricum.hu/", sourceLabel: "Tempus Public Foundation" },
  { name: "DAAD scholarship database", country: "Germany", type: "Scholarship", level: "Master's / PhD", funding: "Varies by programme; many include monthly support", summary: "A searchable database of German Academic Exchange Service funding and study opportunities.", eligibility: "Each award sets its own academic, language and experience requirements.", howToApply: "Filter the official database, open the award's call and submit exactly to the named application office.", source: "https://www.daad.de/en/studying-in-germany/scholarships/daad-scholarships/", sourceLabel: "German Academic Exchange Service" },
  { name: "Türkiye Scholarships", country: "Türkiye", type: "Scholarship", level: "Bachelor's / Master's / PhD", funding: "Tuition, stipend, accommodation and health insurance", summary: "Government-funded awards including university placement for international students.", eligibility: "Academic score, age and programme criteria vary by level.", howToApply: "Register on the official Türkiye Scholarships portal and complete the free online application during the annual call.", source: "https://www.turkiyeburslari.gov.tr/", sourceLabel: "Türkiye Scholarships" },
  { name: "Australia Skilled Independent visa (subclass 189)", country: "Australia", type: "Work route", level: "Skilled professional · no sponsor", funding: "Self-funded migration route; invitation required", summary: "Points-tested permanent residence for eligible skilled workers who are not sponsored by an employer, family member or state.", eligibility: "Occupation on the relevant skilled list, positive skills assessment, competent English, eligible age and enough points.", howToApply: "Submit an Expression of Interest in SkillSelect. If invited, lodge the visa application in ImmiAccount within the invitation period.", source: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-independent-189", sourceLabel: "Australian Department of Home Affairs", documents: ["Passport and identity documents", "English test result", "Skills assessment", "Degree, transcripts and employment evidence", "Police certificates and health examinations"], steps: ["Check the occupation list and points test.", "Obtain an approved English test and skills assessment.", "Create a SkillSelect EOI and wait for an invitation.", "Prepare certified documents and lodge through ImmiAccount.", "Complete health, character and any additional requests."] },
  { name: "Australia Skilled Nominated visa (subclass 190)", country: "Australia", type: "Work route", level: "Skilled professional · state nominated", funding: "Self-funded migration route; state nomination required", summary: "Points-tested permanent residence for skilled workers nominated by an Australian state or territory.", eligibility: "A suitable occupation, skills assessment, English, points and nomination from a participating state or territory.", howToApply: "Submit a SkillSelect EOI, apply for state nomination when that jurisdiction opens its process, then lodge after invitation.", source: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-nominated-190", sourceLabel: "Australian Department of Home Affairs", documents: ["Passport and identity documents", "English test and skills assessment", "Qualifications and transcripts", "Detailed employment references", "Police certificates, health checks and state forms"], steps: ["Review the federal criteria and state nomination requirements.", "Complete your skills assessment and English test.", "Submit an EOI and a state nomination application.", "Accept an invitation and lodge the visa application.", "Respond to health, character and evidence requests."] },
  { name: "Australia Skilled Work Regional visa (subclass 491)", country: "Australia", type: "Work route", level: "Skilled professional · regional", funding: "Temporary regional route with a pathway to permanent residence", summary: "A points-tested regional visa supported by an eligible state or territory or an eligible family sponsor.", eligibility: "Eligible occupation, skills assessment, English, points and regional nomination or family sponsorship.", howToApply: "Submit an EOI, secure nomination or sponsorship, then lodge online after receiving an invitation.", source: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skilled-work-regional-provisional-491", sourceLabel: "Australian Department of Home Affairs", documents: ["Passport and identity documents", "Skills assessment and English result", "Qualification and employment evidence", "Nomination or family sponsor evidence", "Police certificates and health examinations"], steps: ["Confirm the regional occupation and points requirements.", "Prepare English, skills assessment and evidence.", "Submit SkillSelect EOI and seek nomination or sponsorship.", "Lodge the application in ImmiAccount after invitation.", "Meet regional conditions and keep evidence for any later pathway."] },
  { name: "Australia Skills in Demand visa (subclass 482)", country: "Australia", type: "Work route", level: "Employer sponsored professional", funding: "Employer-sponsored temporary route", summary: "Temporary skilled work for an eligible nominated role with an approved Australian sponsor.", eligibility: "An approved sponsor, nominated occupation, relevant skills and any English, salary and work-experience requirements.", howToApply: "Secure an offer from an approved sponsor; the sponsor completes nomination and you lodge the visa application online.", source: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/skills-in-demand-482", sourceLabel: "Australian Department of Home Affairs", documents: ["Passport and identity documents", "Employment offer and nomination details", "Qualifications and employment references", "English evidence where required", "Police certificates and health examinations"], steps: ["Find an employer and confirm the role is eligible.", "Employer submits sponsorship and nomination.", "Collect evidence of skills, experience, English and identity.", "Lodge the application in ImmiAccount and pay the official fee.", "Complete biometrics, health and character checks if requested."] },
  { name: "Canada Express Entry", country: "Canada", type: "Work route", level: "Skilled professional · permanent residence", funding: "Self-funded permanent residence route", summary: "An online system that manages federal skilled-worker immigration applications through a ranked pool.", eligibility: "Language test, eligible work experience, education assessment and a competitive Comprehensive Ranking System score.", howToApply: "Create an Express Entry profile, enter the pool, receive an invitation and submit a complete permanent residence application.", source: "https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html", sourceLabel: "Government of Canada", documents: ["Passport", "Approved language test", "Educational credential assessment", "Employer reference letters", "Proof of funds where required", "Police certificates and medical exam"], steps: ["Take an approved language test and obtain an ECA if needed.", "Calculate eligibility and create an Express Entry profile.", "Enter the pool and monitor invitations.", "Submit the complete application within the deadline if invited.", "Complete biometrics, medical and background checks."] },
  { name: "UK Skilled Worker visa", country: "United Kingdom", type: "Work route", level: "Eligible job offer", funding: "Not a scholarship; salary and sponsorship required", summary: "A work route for an eligible job with an approved UK sponsor.", eligibility: "You need an eligible occupation, a confirmed job offer, salary compliance and a certificate of sponsorship.", howToApply: "Find an employer on the official sponsor register, receive sponsorship and apply on GOV.UK.", source: "https://www.gov.uk/skilled-worker-visa", sourceLabel: "UK Government", documents: ["Valid passport", "Certificate of sponsorship reference", "Proof of English", "Job title, salary and occupation details", "TB test or criminal record certificate where required"], steps: ["Confirm the role and employer are eligible.", "Receive a certificate of sponsorship.", "Prepare English and supporting documents.", "Apply online and pay the visa and health surcharge.", "Attend biometrics and await a decision."] },
  { name: "Germany Opportunity Card", country: "Germany", type: "Work route", level: "Job search", funding: "Not funded; proof of funds required", summary: "A points-based route that can allow qualified applicants to seek work in Germany.", eligibility: "Recognised qualification or points route, language and financial requirements apply.", howToApply: "Check the official eligibility checker and apply through the responsible German mission or foreigners authority.", source: "https://www.make-it-in-germany.com/en/visa-residence/opportunity-card", sourceLabel: "Make it in Germany (Federal Government)", documents: ["Passport and proof of nationality", "Recognised qualification or evidence for the points route", "Language certificate", "Proof of funds", "Health insurance and accommodation evidence"], steps: ["Check recognition and points eligibility.", "Prepare language, qualification and financial proof.", "Book the responsible mission or authority appointment.", "Submit the visa or residence application.", "Search for eligible work while observing the route conditions."] },
];

export const countryGuides = [
  { country: "United Kingdom", universities: "Oxford, Cambridge, Imperial, UCL, Edinburgh", portal: "https://www.ucas.com/", visa: "https://www.gov.uk/student-visa" },
  { country: "Australia", universities: "Melbourne, Sydney, UNSW, Monash, ANU", portal: "https://www.studyaustralia.gov.au/", visa: "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500" },
  { country: "Germany", universities: "TUM, LMU Munich, Heidelberg, RWTH Aachen, Humboldt", portal: "https://www.daad.de/en/studying-in-germany/", visa: "https://www.make-it-in-germany.com/en/visa-residence/types/studying" },
  { country: "Japan", universities: "University of Tokyo, Kyoto, Osaka, Tohoku, Nagoya", portal: "https://www.studyinjapan.go.jp/en/", visa: "https://www.mofa.go.jp/j_info/visit/visa/long/visa6.html" },
  { country: "Canada", universities: "Toronto, McGill, UBC, Alberta, Waterloo", portal: "https://www.educanada.ca/index.aspx?lang=eng", visa: "https://www.canada.ca/en/immigration-refugees-citizenship/services/study-canada.html" },
  { country: "United States", universities: "MIT, Stanford, Harvard, Michigan, Cornell", portal: "https://educationusa.state.gov/", visa: "https://travel.state.gov/content/travel/en/us-visas/study/student-visa.html" },
];
